"""The app-server protocol's TypeScript types for the desktop app's Work window.

Work talks to `mling app-server` (specs/DREAMFERENCE_MIGHTLING_DESKTOP.md §4.4), so its types must be
the ones the pinned Codex speaks, never copied from a newer Codex or from another client. They are
not generated by running anything: `codex app-server generate-ts --experimental` writes the
`typescript` map of a precomputed export the Codex source carries
(`app-server-protocol/schema/precomputed/app-server-exports-experimental.json.zst`, compiled into
the binary with `include_bytes!`), trimming trailing whitespace from each line. Reading the same
file from the submodule gives byte for byte what the pinned binary would write, with no binary and
no model server. The generated files are committed under `desktop/ui/src/protocol`; a test
regenerates them and fails on any difference, so a Codex bump that moves the protocol fails the
build rather than the UI.
"""

import json
import re
import shutil
import subprocess
from pathlib import Path
from typing import Final

from dreamference.chat.desktop_runner import DESKTOP_PROJECT_DIR
from dreamference.runner.codex_branded_builder import CODEX_SUBMODULE_DIR

# The precomputed export `generate-ts --experimental` writes from (`precomputed_exports.rs`).
EXPERIMENTAL_EXPORTS: Final[Path] = (
    Path(CODEX_SUBMODULE_DIR) / "codex-rs" / "app-server-protocol" / "schema" / "precomputed"
    / "app-server-exports-experimental.json.zst"
)

# Where Work's frontend keeps the generated types.
PROTOCOL_DIR: Final[Path] = Path(DESKTOP_PROJECT_DIR) / "ui" / "src" / "protocol"

# `trim_trailing_line_whitespace` in `precomputed_exports.rs`: spaces and tabs before each newline.
TRAILING_WHITESPACE: Final[re.Pattern] = re.compile(r"[ \t]+(?=\n|\Z)")


class DesktopProtocolTypes:
    """Writes and checks the generated protocol types; classmethods only."""

    @classmethod
    def has_source(cls) -> bool:
        """Tells whether the types can be generated here.

        A checkout has the Codex submodule, and `zstd` reads its export. A release install has
        neither and needs neither.

        Returns:
            bool: True when both are present.
        """
        return EXPERIMENTAL_EXPORTS.is_file() and shutil.which("zstd") is not None

    @classmethod
    def exports(cls, source: Path = EXPERIMENTAL_EXPORTS) -> dict[str, str]:
        """Reads the files `generate-ts --experimental` would write.

        Args:
            source: The compressed export.

        Returns:
            dict[str, str]: Relative path to contents, trailing whitespace trimmed as Codex trims it.
        """
        raw = subprocess.run(["zstd", "-dc", str(source)], capture_output=True, check=True).stdout
        typescript = json.loads(raw)["typescript"]
        return {path: TRAILING_WHITESPACE.sub("", text) for path, text in typescript.items()}

    @classmethod
    def write(cls, out_dir: Path = PROTOCOL_DIR) -> int:
        """Replaces `out_dir` with freshly generated types.

        Args:
            out_dir: The folder to write; anything already in it is removed first.

        Returns:
            int: The number of files written.
        """
        exports = cls.exports()
        shutil.rmtree(out_dir, ignore_errors=True)
        for relative, text in exports.items():
            path = out_dir / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="")
        return len(exports)

    @classmethod
    def drift(cls, out_dir: Path = PROTOCOL_DIR) -> list[str]:
        """Compares the committed types with what the pinned Codex would generate.

        Args:
            out_dir: The committed types.

        Returns:
            list[str]: One line per file that is missing, extra or different; empty when in step.
        """
        expected = cls.exports()
        found = {
            path.relative_to(out_dir).as_posix(): path.read_bytes().decode("utf-8")
            for path in out_dir.rglob("*") if path.is_file()
        }
        lines = [f"missing: {path}" for path in sorted(expected.keys() - found.keys())]
        lines += [f"not generated by the pinned Codex: {path}"
                  for path in sorted(found.keys() - expected.keys())]
        lines += [f"differs: {path}" for path in sorted(expected.keys() & found.keys())
                  if expected[path] != found[path]]
        return lines
